baseURL = "https://DavidDevGear.github.io/"
title = "Dev Gear Reviews"
languageCode = "en-us"

# ðŸš« NO THEME
#theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreLogs = ["warning-goldmark-raw-html"]

[params]
  description = "Gaming hardware reviews from a game developer's perspective"
  email = "daveadebayo842@gmail.com"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Reviews"
  url = "/reviews/"
  weight = 20

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 30

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 40

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 50

[[menu.main]]
  name = "Disclosure"
  url = "/disclosure/"
  weight = 60

[[params.social]]
  name = "Twitterâ†—"
  url = "https://twitter.com/DvidDaDev"

[[params.social]]
  name = "GitHubâ†—"
  url = "https://github.com/DavidDevGear"

[[params.social]]
  name = "Itch.ioâ†—"
  url = "https://sovereigntydigital.itch.io"

[params.amazon]
  tag = "dviddadev2109-20"
  region = "us"
[taxonomies]
category = "categories"
tag = "tags"
